### ISSUE TITLE
How to build an uninst.exe with squirrel.windows?

### ISSUE THREAD

**Issue by radiorz** [electron-forge/electron-forge-docs#57] opened 2021-12-30 09:45 UTC
I am glad to use electron-forge to build my electron apps. 
But it seems that there are not description about how to build an uninst.exe  in docs.

**Comment by malept** [comment] 2022-02-14 07:10
Duplicate of https://github.com/electron-userland/electron-forge/issues/2660

**Closed as completed by malept** 2022-02-14 07:10 UTC
Labels: duplicate
