### ISSUE TITLE
Starting a project (dev server) created with webpack template throws an error

### ISSUE THREAD

**Issue by yevgeniyvaleyev** [electron-forge/electron-forge-docs#46] opened 2021-05-20 09:04 UTC
- OS: mac os
- Initialization : `yarn create electron-app my-new-app --template=typescript-webpack` - `ok`
- App Make: works fine - `ok`
- Start dev app : fails : 

```
> my-new-app@1.0.0 start /Users/***/dev/my-new-app
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Compiling Main Process Code
✖ Launch Dev Servers

An unhandled error has occurred inside Forge:
Invalid options object. Dev Middleware has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'historyApiFallback'. These properties are valid:
   object { mimeTypes?, writeToDisk?, methods?, headers?, publicPath?, stats?, serverSideRender?, outputFileSystem?, index? }
ValidationError: Invalid options object. Dev Middleware has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'historyApiFallback'. These properties are valid:
   object { mimeTypes?, writeToDisk?, methods?, headers?, publicPath?, stats?, serverSideRender?, outputFileSystem?, index? }
    at validate (/Users/***/dev/my-new-app/node_modules/webpack-dev-middleware/node_modules/schema-utils/dist/validate.js:104:11)
    at wdm (/Users/***/dev/my-new-app/node_modules/webpack-dev-middleware/dist/index.js:31:29)
    at /Users/***/dev/my-new-app/node_modules/@electron-forge/plugin-webpack/src/WebpackPlugin.ts:292:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-new-app@1.0.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-new-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2021-05-20T08_51_47_234Z-debug.log
```

I cannot find the reason why it fails (and searching the issue in internet also did not help)

**Comment by yevgeniyvaleyev** [comment] 2021-05-20 09:10
throws the same issue for all initialisations with template: only webpack, only typescript and both

**Comment by yevgeniyvaleyev** [comment] 2021-05-20 09:13
Excuses, with typescript template work ok, it fails only if webpack included

**Comment by malept** [comment] 2021-05-20 17:49
Duplicate of https://github.com/electron-userland/electron-forge/issues/2273

**Closed as completed by malept** 2021-05-20 17:49 UTC
